"""
VinSight Analyst Service
Powered by Groq & Llama 3.3 70B
"""

import os
import logging
import json
from typing import Dict, Optional
from groq import Groq

logger = logging.getLogger(__name__)

class AnalystService:
    """
    AI Portfolio Analyst that answers natural language questions about the user's portfolio.
    """
    
    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or os.getenv("GROQ_API_KEY")
        if not self.api_key:
            logger.warning("No Groq API key found. Analyst features will be disabled.")
            self.client = None
        else:
            self.client = Groq(api_key=self.api_key)
            
        self.model = "llama-3.3-70b-versatile"

    def is_available(self) -> bool:
        return self.client is not None

    def chat(self, query: str, portfolio_context: Dict) -> str:
        """
        Generates an insight or answer based on the user's query and portfolio state.
        
        Args:
            query: User's natural language question (e.g. "Why is my Apple stock down?", "Is my portfolio diversified?")
            portfolio_context: Dictionary containing portfolio summary, holdings, and score results.
        
        Returns:
            String response from the AI analyst.
        """
        if not self.client:
            return "I'm sorry, my AI brain (Groq API) is not configured. Please check your API keys."

        try:
            # 1. format context for the LLM
            context_str = json.dumps(portfolio_context, indent=2)
            
            # 2. Construct System Prompt
            system_prompt = f"""You are VinSight, a Senior Portfolio Analyst at a top-tier hedge fund.
            
            YOUR MANIFESTO:
            - You are data-driven, cynical, and sophisticated.
            - You do NOT give generic financial advice (e.g. "consult a professional"). You give ANALYSIS.
            - You rely STRICTLY on the provided PORTFOLIO CONTEXT.
            - If the user asks about a stock NOT in the portfolio, look at the available market context if any, or say you don't track it.
            
            PORTFOLIO CONTEXT:
            {context_str}
            
            USER QUERY:
            {query}
            
            INSTRUCTIONS:
            - Answer the user's query directly.
            - Cite specific numbers (scores, weights, metrics) from the context.
            - If the portfolio has a high concentration risk (referenced in 'modifications'), warn them.
            - Keep responses concise (under 3-4 sentences/bullets) unless asked for deep dive.
            - Tone: Professional, slightly opinionated (if score is low, say it's garbage).
            """

            # 3. Call Groq
            chat_completion = self.client.chat.completions.create(
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": query}  # Redundant but standard chat format
                ],
                model=self.model,
                temperature=0.3, # Low temp for factual consistency
                max_tokens=600
            )
            
            return chat_completion.choices[0].message.content

        except Exception as e:
            logger.error(f"Error in AnalystService chat: {e}")
            return "I encountered an error analyzing your request. Please try again."

    def validate_score(self, ticker: str, score_result: Dict, deep_data: Dict) -> Dict:
        """
        Acts as the 'CIO' (Chief Investment Officer) to validate the mathematical score.
        Compares the algorithmic ScoreResult against the 'Deep Data' (Earnings, Insiders, etc).
        
        Returns:
            Dict: {
                "verdict": "VALIDATED" | "DIVERGENCE" | "TURNAROUND",
                "color": "green" | "orange" | "purple",
                "explanation": "..."
            }
        """
        if not self.client:
            return {"verdict": "UNAVAILABLE", "color": "gray", "explanation": "AI Analyst not configured."}

        try:
            # 1. Prepare Context
            context_str = json.dumps({
                "ticker": ticker,
                "math_score": score_result.get('total_score'),
                "math_rating": score_result.get('rating'),
                "deep_data": deep_data
            }, indent=2, default=str)

            # 2. System Prompt
            system_prompt = f"""You are the CIO (Chief Investment Officer) of a top hedge fund.
            Your job is to VALIDATE the algorithmic score generated by our quant model ("VinSight").
            
            INPUT context contains:
            1. Math Score (0-100) & Rating.
            2. Deep Data (Earnings Trend, Smart Money/Insider Activity, Analyst Targets).
            
            YOUR TASK:
            Determine if the Math Score is trustworthy or if there is a signal divergence.
            
            OUTPUT RULES (JSON ONLY):
            Return a JSON object with:
            - "verdict": One of ["VALIDATED", "DIVERGENCE", "TURNAROUND"]
            - "color": One of ["green", "orange", "purple"]
            - "explanation": Max 2 sentences.
            
            LOGIC:
            - VALIDATED (Green): Math Score aligns with Insiders/Earnings. (e.g. High Score + Buying, or Low Score + Selling).
            - DIVERGENCE (Orange): Math Score is HIGH, but Insiders are Selling heavily or Earnings are deteriorating. (Trap).
            - TURNAROUND (Purple): Math Score is LOW, but Smart Money is Buying or Earnings Turnaround detected. (Hidden Gem).
            
            CONTEXT:
            {context_str}
            """

            # 3. Call Groq
            chat_completion = self.client.chat.completions.create(
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": f"Validate the score for {ticker}."}
                ],
                model=self.model,
                temperature=0.2,
                response_format={"type": "json_object"}
            )
            
            return json.loads(chat_completion.choices[0].message.content)

        except Exception as e:
            logger.error(f"Error in AnalystService validate_score: {e}")
            return {"verdict": "ERROR", "color": "gray", "explanation": "AI Validation failed."}
